### PR TITLE
Php8

### PR DESCRIPTION
**Pull request by nono303**

### CODE REVIEW

**Comment by nono303** [comment]
tested on php-8.0.0

**Comment by nono303** [comment]
tested on php-8.0.0 VS16 NTS x64

**Comment by eisberg** [comment]
@nono303 thanks! 

On the php 7.4 version, did you check BC?

**Comment by nono303** [comment]
> On the php 7.4 version, did you check BC?

BC ?
I did not change, add or remove any check, just ported linux ones in windows format

**Comment by nono303** [comment]
thanks @eisberg

**Pull request merged**
